# Generated by Django 3.1.7 on 2021-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mail', models.DateField(verbose_name='Дата')),
                ('sent_to', models.CharField(max_length=50, verbose_name='Кому')),
                ('sender', models.CharField(max_length=50, verbose_name='От кого')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mail', models.TextField(verbose_name='Писмо')),
                ('executor', models.CharField(max_length=50, verbose_name='Исполнитель')),
            ],
        ),
    ]
