# Generated by Django 3.1.7 on 2021-03-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210320_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='executor',
        ),
        migrations.AlterField(
            model_name='mail',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.org', verbose_name='Кому'),
        ),
    ]
