# Generated by Django 3.1.7 on 2021-03-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210320_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='o_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя организаций'),
        ),
    ]
