# Generated by Django 3.1.7 on 2021-03-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_org_o_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['date_mail']},
        ),
        migrations.RenameField(
            model_name='org',
            old_name='o_name',
            new_name='org_name',
        ),
        migrations.AddField(
            model_name='mail',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.staff'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date_mail',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.TextField(null=True, verbose_name='Писмо'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.CharField(max_length=50, null=True, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sent_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.org'),
        ),
        migrations.AlterField(
            model_name='org',
            name='f_name',
            field=models.CharField(max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='org',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='f_name',
            field=models.CharField(max_length=50, null=True, verbose_name='ФИО исполнителя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
