# Generated by Django 3.1.7 on 2021-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210320_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='nomer',
            field=models.IntegerField(null=True, verbose_name='Исходяший номер'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
