# Generated by Django 3.1.7 on 2021-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210320_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='nomer',
            field=models.IntegerField(null=True, unique=True, verbose_name='Исходяший номер'),
        ),
    ]
